import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import "../app/globals.css"; // Import your CSS file (create styles.css)
import type { ReactNode } from "react";
import Image from "next/image";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "M.FK Portfolio",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="body">
        <header className="header">
          <nav className="container">
            <div className="flex-items">
              <Image
                src="/images/M.fk Logo.png"
                alt="Logo"
                width={30}
                height={20}
                className="image-logo"
              />
              <span className="logo-text">M.Fk</span>
            </div>
            <ul className="nav-list">
              <li><Link href="/" className="nav-link">Home</Link></li>
              <li><Link href="/about" className="nav-link">About</Link></li>
              <li><Link href="/projects" className="nav-link">Projects</Link></li>
              <li><Link href="/contact" className="nav-link">Contact</Link></li>
            </ul>
          </nav>
        </header>
        <main className="main">
          {children}
        </main>
        <footer className="footer">
          <p>© 2024 My Website</p>
        </footer>
      </body>
    </html>
  );
};

export default Layout;

